### ISSUE TITLE
Action `cda-tum/setup-z3@v1.0.8` is broken on `ubuntu-latest`

### ISSUE THREAD

**Issue by wenkokke** [cda-tum/setup-z3#100] opened 2023-02-06 15:52 UTC
It seems the action is broken on `ubuntu-latest`:
```
# output of cda-tum/setup-z3@v1
/usr/bin/unzip -o -q /home/runner/work/_temp/4165730e-84ca-4d14-ae38-4aca23556260

# ...

# output of ls -al ${{ steps.setup-z3.outputs.z3-root }}/z3
ls:
  cannot access '/opt/hostedtoolcache/z3/latest/x64/z3-4.12.1-x64-glibc-2.35/z3':
  No such file or directory
```
See, for instance, this workflow run:
<https://github.com/wenkokke/setup-agda/actions/runs/4105314331/jobs/7081992236#step:5:9>

**Comment by burgholzer** [comment] 2023-02-06 16:06
Hey,
Thanks for bringing this up. I'll look into it asap and will get back to you!
Could be that Z3 changed the naming scheme of the release artifacts again.

**Comment by wenkokke** [comment] 2023-02-06 16:29
It seems the issue is simply that the path to z3 moved from `${{ steps.setup-z3.outputs.z3-root }}/z3` to `${{ steps.setup-z3.outputs.z3-root }}/bin/z3`, see #101.

**Comment by burgholzer** [comment] 2023-02-06 16:33
That has actually always been the case. `$Z3_ROOT` merely points to the root of the directory.
This contains:
 - the `z3` binary in the `bin` folder
 - the header files in the `include` directory
 - the library files in the `lib` directory (or in the `bin` directory on some OSes)

So, to me, it seems like everything is still working as intended. Please let me know if I missed something.

**Comment by burgholzer** [comment] 2023-02-07 13:06
Closing this for now, and thanks for the PR. Seems like a good sanity check.
Feel free to re-open or create another issue if you should stumble upon further problems.

**Closed** 2023-02-07 13:05 UTC
